name: steps_indicator
description: Flutter plugin to display a simple steps indicator line widget.
version: 1.1.0
homepage: https://github.com/huextrat/steps_indicator

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter